### RAG 查询：代码提交规范
POST http://localhost:8080/api/v1/rag/query
Content-Type: application/json

{
  "question": "代码提交需要遵守什么规范？",
  "kbIds": [2]
}

### RAG 查询：量子计算原理
POST http://localhost:8080/api/v1/rag/query
Content-Type: application/json

{
  "question": "量子计算原理是什么？",
  "kbIds": [1]
}

### RAG-V2 查询：年假规定
POST http://localhost:8080/api/v1/rag/query
Content-Type: application/json

{
  "question": "年假是怎么规定的？",
  "kbIds": [1]
}

### RAG 查询：Commit Message 格式要求
POST http://localhost:8080/api/v1/rag/query
Content-Type: application/json

{
  "question": "Commit Message格式要求是什么？",
  "kbIds": [2]
}


### RAG 查询：新同事开发电脑配置
POST http://localhost:8080/api/v1/rag/query
Content-Type: application/json

{
  "question": "新来的同事怎么配置开发电脑？",
  "kbIds": [1]
}