### RAG 查询：新员工第一天要干嘛
POST http://localhost:8080/api/v1/rag/query
Content-Type: application/json

{
  "question": "新员工第一天要干嘛",
  "kbIds": [1]
}


### RAG 查询：代码提交规范
POST http://localhost:8080/api/v1/rag/query
Content-Type: application/json

{
  "question": "代码提交规范",
  "kbIds": [2]
}